
path: C:\Users\Marcelo\Documents\Python Scripts\scripts_para_aprendizado\aprendendo_yolo\train-yolov8-custom-dataset-step-by-step-guide\data\  # dataset root dir
train: images\train  # train images (relative to 'path')
val: images\val  # val images (relative to 'path')

# Classes
names:
  0: alpaca
